docs/source/api.rst
Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>
#7
=> docs: sidetree-node api doc update

api/swagger.yaml, cmd/sidetree-server/main.go, restapi/doc.go, restapi/embedded_spec.go, restapi/operations/sidetree_api.go
Remove Securkey from description in swagger file
Closes #13
=> chore: Modify description in swagger file

test/bddtests/did_sidetree_steps.go
=> fix: remove panic from did_sidetree_steps

pkg/requesthandler/operationhandler.go
=> fix: Add ID to create operation

go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Update to the latest core library

go.mod, go.sum, pkg/context/context.go, pkg/mocks/cas.go, pkg/observer/observer.go, pkg/observer/observer_test.go, restapi/configure_sidetree.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
=> feat: Add poll observer

.golangci.yml, scripts/check_lint.sh
Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>
=> ci: GolangCI Lint - Update docker image source and remove webhook config

api/swagger.yaml, go.mod, go.sum, pkg/requesthandler/operationhandler.go, pkg/requesthandler/resolutionhandler.go, pkg/requesthandler/response.go, pkg/requesthandler/response_test.go, restapi/doc.go, restapi/embedded_spec.go, restapi/operations/sidetree_api.go, test/bddtests/fixtures/config/didDocument.json, test/bddtests/go.mod, test/bddtests/go.sum, test/bddtests/restclient/sender.go
=> feat: Return did document in resp body

pkg/observer/observer.go, pkg/observer/observer_test.go
=> fix: observer pull not updating last txn number that pulled

.travis.yml, ci/azp-dependencies.yml, ci/azure-pipelines.yml
=> ci: Azure pipelines

README.md
=> ci: update README build badge to azp

ci/azure-pipelines.yml
=> chore: Push sidetree image to dockerhub after merge

ci/azure-pipelines.yml
=> fix: fix azure pipeline

ci/azure-pipelines-merge.yml, ci/azure-pipelines-pr.yml
=> chore: Add merge azure pipeline

README.md
=> chore: Update azure status badge

README.md
=> fix: fix readme file

ci/azure-pipelines.yml
=> fix: publish build is broken

go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Update sidetree-core-go revision

Makefile, ci/azure-pipelines.yml, ci/version_var.sh
=> chore: Release v0.1.0

ci/version_var.sh
=> chore: Change release version to 0.1.1

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
=> feat: Add test for DID resolution with initial-values parameter

Makefile, cmd/sidetree-server/main.go, go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Point to latest sidetree-core-go

ci/version_var.sh, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Release v0.1.1

ci/version_var.sh
=> chore: Change release version to 0.1.2

ci/azure-pipelines.yml
=> chore: push images to docker.pkg.github.com

go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Update to latest sidetree core
Closes #104
=> chore: Update to latest sidetree-core

go.mod, go.sum, pkg/observer/observer.go, pkg/observer/observer_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Update to latest sidetree-core and create test for delete document.
Closes #108
=> feat: Support for delete document

ci/version_var.sh, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Release 0.1.2

ci/version_var.sh
=> chore: Post Release v.0.1.2

cmd/sidetree-server/main.go, go.mod, go.sum, pkg/context/context.go, test/bddtests/go.mod, test/bddtests/go.sum
Use the in-memory implementation for the operation queue.
closes #113
=> chore: Use in-memory operation queue

cmd/sidetree-server/main.go, test/bddtests/bddtests_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/fixtures/docker-compose.yml, test/bddtests/go.mod, test/bddtests/go.sum
=> feat: Make did namespace configurable

go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Create request is no longer signed request. Update to latest sidetree-core.
Closes #120
=> chore: Update sidetree-core (create no longer signed request)

ci/azure-pipelines.yml, go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Create, update and revoke requests modified.
Closes #122
=> chore: Update to latest sidetree-mock

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
And new BDD test to update document using JSON patch
Closes #124
=> test: Add update document BDD test

go.mod, go.sum, pkg/observer/observer.go, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Update to latest sidetree-core-go

Makefile, cmd/sidetree-server/main.go, pkg/httpserver/server.go, pkg/httpserver/server_test.go, scripts/generate_test_keys.sh, test/bddtests/did_sidetree_steps.go, test/bddtests/restclient/sender.go
=> feat: Enable tls for sidetree-mock server

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/fixtures/config/recover.json, test/bddtests/go.mod, test/bddtests/go.sum
Add bdd test for document recovery
Closes #129
=> feat: Add document recovery

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
update to latest sidetree-core
Closes #130
=> chore: update sidetree-core (otp renamed)

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Add test for adding and removing public key patches
Closes #140
=> feat: Add/remove public keys patches

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Sidetree-core now supports adding and removing service endpoints. Add BDD test to demonstrate this capability.
Closes #142
=> feat: Add/remove service endpoints test

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
-- handle key usage property
-- revoke renamed to deactivate
Closes #150
=> chore: Update sidetree-core

test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature
Rename revoke to deactivate in feature file and corresponding functions
Closes #152
=> fix: Rename revoke to deactivate in feature file

go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Sidetree-core has been updated to return result set
Closes #155
=> chore: Update sidetree-core - return result set

go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Signature for resoultion with initial state has been changed in sidetree-core
Closes #165
=> chore: Update sidetree-core - Resolve with initial state

go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Rename sidetree update endpoint to /operations

go.mod, go.sum, pkg/httpserver/server_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Additional server side validation
Closes #172
=> chore: update sidetree-core - server side validation

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
initial state param order fix
Closes #177
=> chore: update sidetree core

go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
- 'replace' patch removed
Closes #179
=> chore: Update sidetree-core - 'replace' patch removed

go.mod, go.sum
=> chore: update sidetree-core (capability usage)

cmd/sidetree-server/main.go, pkg/httpserver/server.go, pkg/httpserver/server_test.go
=> feat: bearer authorization token support

go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
- revert to original pub key ID validation
Closes #191
=> chore: update sidetree-core - revert to original pub key ID validation

ci/version_var.sh, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Release v0.1.3

ci/version_var.sh
=> chore: Complete release v0.1.3

ci/azure-pipelines.yml, ci/version_var.sh
=> ci: publish snapshot images to snapshot repo

ci/version_var.sh
=> chore: drop arch prefix on version tags

go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
JWS model changed from struct to compact JWS string
Closes #203
=> chore: update sidetree-core (JWS model change)

cmd/sidetree-server/main.go, go.mod, go.sum, pkg/mocks/protocol.go, pkg/observer/observer.go, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
- txn handler
- anchor string changes
Closes #209
=> chore: update sidetree-core (txn handler/anchor string)

go.mod, go.sum, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Core changes:
- namespace removed from batch files
- namespace added to Sidetree transaction
Closes #211
=> chore: update-sidetree core (add namespace to txn)

Makefile, go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
This allows 'priority' attribute in diddoc `service`
Signed-off-by: George Aristy <george.aristy@securekey.com>
=> chore: update sidetree-core-go

go.mod, go.sum, pkg/mocks/operationstore.go, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Changes include:
- anchored operation model
Closes #226
=> chore: update sidetree-core (anchored operation)

go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/go.mod, test/bddtests/go.sum
- added function to retrieve protocol by transaction (block) number
Add  implementation of this function to protocol client.
Closes #231
=> chore: update sidetree core (get protocol by txn number)

go.mod, go.sum, pkg/mocks/protocol.go
Update sidetree-core; add signature and key algorithms configuration/validation
Closes #237
=> chore: update sidetree-core; add signing/key algorithms validation

go.mod, go.sum, pkg/httpserver/server_test.go, pkg/mocks/protocol.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Changes include:
- support for JsonWebKey2020
- rename protocol parameters
Closes #239
=> chore: update sidetree-core; JsonWebKey2020, rename protocol params

cmd/sidetree-server/main.go, go.mod, go.sum, test/bddtests/fixtures/docker-compose.yml, test/bddtests/go.mod, test/bddtests/go.sum
Add ability to configure method context
Closes #243
=> chore: Add ability to configure method context

ci/version_var.sh, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Release v0.1.4

ci/version_var.sh
Closes #249
Complete release v0.1.4
=> chore: Complete release v0.1.4

go.mod, go.sum, pkg/mocks/protocol.go
=> chore: Updated to latest sidetree-core-go

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
- new additional long form format for did resolution
Closes #255
=> chore: update sidetree-core (additional long format)

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/interop.feature, test/bddtests/go.mod, test/bddtests/go.sum
Add integration tests for "request" and "resolution" type errors (based on operation)
Closes #261
=> chore: Add integration tests for "request" and "resolution" type errors

go.mod, go.sum, scripts/integration.sh, test/bddtests/did_sidetree_steps.go, test/bddtests/features/interop.feature, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core and add long form DID JCS resolution interop test.
Closes #269
=> chore: Add long form DID resolution interop test

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/interop.feature, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core (deprecate init-state parameter)
Closes #271 
=> chore: Update sidetree-core (deprecate init-state parameter)

cmd/sidetree-server/main.go, go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/fixtures/docker-compose.yml, test/bddtests/go.mod, test/bddtests/go.sum
Included:
- add configuration for namespace aliases
- update sidetree-core (support for cannonical ID)
- add integration tests for resolving documents with alias
Closes #273
=> chore: Add canonical id, configuration for namespace aliases

go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core: generic enable patch parameter
Closes #275
=> chore: update sidetree-core (generic patches parameter)

go.mod, go.sum, pkg/httpserver/server.go, pkg/mocks/protocol.go, pkg/observer/observer_test.go, scripts/integration.sh, test/bddtests/did_sidetree_steps.go, test/bddtests/features/interop.feature, test/bddtests/go.mod, test/bddtests/go.sum
- update sidetree-core (JSON API changes according to style guide)
- refactor integration tests as per latest interop test vectors
Closes #283
=> chore: Refactor integration tests as per latest test vectors

go.mod, go.sum, pkg/mocks/protocol.go, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Included: download and verify proof files
Closes #291
=> chore: update sidetree-core (download/verify proof files)

go.mod, go.sum, pkg/httpserver/server_test.go, pkg/mocks/protocol.go, pkg/observer/observer_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Remove hashAlgorithm protocol parameter
Closes #293
=> chore: update sidetree-core (remove hashAlgorithm)

go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
For anchor string: rename anchor address to core index file URI (spec change)
Closes #297
=> chore: update sidetree-core (rename anchor address)

cmd/sidetree-server/main.go, go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Add document transformer to protocol version
Closes #299
=> chore: Add document transformer to protocol version

go.mod, go.sum, pkg/mocks/operationstore.go, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core: support for service endpoint as object
Closes #303
=> chore: update sidetree-core (suport service endpoint as object)

ci/version_var.sh, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Release v0.1.5

ci/version_var.sh
Complete release v0.1.5
Closes #309
=> chore: Complete release v0.1.5

Makefile, ci/azure-pipelines.yml, ci/version_var.sh, images/sidetree-mock/Dockerfile, test/bddtests/fixtures/.env
=> ci: migrate to ghcr

go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/interop.feature, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core (align with did core)
Closes #314
=> chore: update sidetree-core (align with did core)

ci/azure-pipelines.yml
=> chore: rename master branch to main

README.md
=> chore: rename branches in README

pkg/httpserver/server.go
=> fix: cors option

go.mod, go.sum, pkg/observer/observer_test.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/interop.feature, test/bddtests/go.mod, test/bddtests/go.sum
- deactivated returns HTTP 200 + deactivated flag
Closes #319
=> chore: Update sidetree-core (deactivated returns 200)

cmd/sidetree-server/main.go, go.mod, go.sum, pkg/context/context.go, pkg/observer/observer.go, pkg/observer/observer_test.go, test/bddtests/go.mod, test/bddtests/go.sum
Included:
- rename blockchain client
- anchor origin/times
Closes #322
=> chore: update sidetree-core(rename blockchain client, anchor times/origin)

cmd/sidetree-server/main.go, docs/source/api.rst, docs/source/conf.py, pkg/httpserver/server_test.go, test/bddtests/did_sidetree_steps.go
Change version in URLs
Closes #328
=> chore: Change version in URLs

ci/version_var.sh, go.mod, go.sum, test/bddtests/go.mod, test/bddtests/go.sum
=> chore: Release v0.6.0

ci/version_var.sh
Complete release 0.6.0
Closes #332
=> chore: Complete release 0.6.0

cmd/sidetree-server/main.go, go.mod, pkg/discovery/endpoint/restapi/model.go, pkg/discovery/endpoint/restapi/openapi.go, pkg/discovery/endpoint/restapi/operations.go, pkg/discovery/endpoint/restapi/operations_test.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/features/interop.feature, test/bddtests/fixtures/docker-compose.yml, test/bddtests/go.mod
=> feat: add mock wellknown endpoints

cmd/sidetree-server/main.go, go.mod, go.sum, test/bddtests/did_sidetree_steps.go, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core and add new service endpoint test cases:
- string (has to be valid URI)
- list of strings (each has to be valid URI)
- an object
- list of objects
Closes #341
=> chore: Update sidetree-core and add new service endpoint test cases

go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/go.mod, test/bddtests/go.sum
Update to sidetree-core rc2
Close #344
=> chore: Update to sidetree-core rc2

go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Add tests for alsoKnownAs
Closes #346
=> chore: Add tests for alsoKnownAs

go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/did_sidetree_steps.go, test/bddtests/features/did-sidetree.feature, test/bddtests/go.mod, test/bddtests/go.sum
Update sidetree-core-go (custom patches for AlsoKnownAs)
Closes #348
=> chore: Update sidetree-core-go (custom patches for AlsoKnownAs)

go.mod, go.sum, pkg/mocks/protocol.go, test/bddtests/go.mod, test/bddtests/go.sum
Renamed also known patches
Closes #350
=> chore: update sidetree-core (rename alsoKnownAs patches)
