trustbloc/sidetree-mock

go.mod
go.sum
test/bddtests/go.mod
test/bddtests/go.sum

chore: Update sidetree-core-go revision to v0.1.0

---

cmd/sidetree-server/main.go
go.mod
go.sum
pkg/context/context.go
pkg/mocks/operationstore.go
pkg/observer/observer.go
pkg/observer/observer_test.go
test/bddtests/go.mod
test/bddtests/go.sum

Point to latest sidetree-core-go which allows for a different operation store for each namespace.
closes #138

chore: Update to latest sidetree-core-go

---

cmd/sidetree-server/main.go
docs/source/api.rst
go.mod
go.sum
pkg/httpserver/server_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Also updated the base path to /sidetree/0.0.1 to make it compatible with the spec.
closes #171

chore: Renamed resolution endpoint to /identifiers

---

go.mod
go.sum
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Sidetree changes include:
- kid must not be provided for recovery and deactivate
- kid must be provided for update
- helper signers accommodated for those scenarios
- add signing model for update, not just string (DELTA_HASH)
- remove option to update document using recovery key (document has to have at least one ops key)
- check delta against signed delta hash for update and recovery
- validate info against signed data for deactivate
- update document context as per latest spec
- resolution returns bad request in case of validation error
Closes #175

chore: update sidetree-mock

---

go.mod
go.sum
pkg/httpserver/server_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Included:
- add service patch validation
- pub key and service id validation
- initial document validation includes services
- validation of all patches when parsing operation deltas (before operation is accepted)
- remove public keys and remove services patch validation
Close #185

chore: Update sidetree-core - service validation

---

Makefile
ci/azure-pipelines.yml
images/sidetree-mock/Dockerfile

Rename sidetree to sidetree-mock in Makefile, Dockerfile, Azure pipelines to be consistent with other projects.
Closes #198

chore: Rename sidetree to sidetree-mock

---

cmd/sidetree-server/main.go
go.mod
go.sum
pkg/httpserver/server_test.go
pkg/observer/observer_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Sidetree core has been modified with commitment changes:
- generate recovery and update commitments from corresponding public JWK during create
- add update key to update request
- add recovery key for deactivate and recover requests
- validate keys against previously provided commitments
- validate signature against passed in keys
- return update and recovery commitments in resolution result metadata (remove recovery key and operation keys)
Closes #217

chore: update sidetree-core (commitment changes)

---

go.mod
go.sum
pkg/mocks/protocol.go
test/bddtests/go.mod
test/bddtests/go.sum

Enable replace patch action in order to run interop tests.
Closes #234

chore: update sidetree-core (enable replace patch action param)

---

go.mod
go.sum
test/bddtests/go.mod
test/bddtests/go.sum

Update to latest sidetree-core. Changes included:
- removed "ops" purpose
- if applying patch fails we should continue to the next patch
- removed validation of optional service parameters
- fixed 'resolution loops indefinitely when operation's commitment equals next operation commitment'
Closes #241

chore: update sidetree-core

---

go.mod
go.sum
pkg/httpserver/server_test.go
pkg/mocks/protocol.go
scripts/integration.sh
test/bddtests/bddtests_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/features/interop.feature
test/bddtests/go.mod
test/bddtests/go.sum

- double hash JWK for commitment
- reorganize interop tests since they were changed to use same create for testing all operations
Closes #253

chore: update sidetree-core (double hash JWK for commitment)

---

go.mod
go.sum
scripts/integration.sh
test/bddtests/go.mod
test/bddtests/go.sum

Included:
- refactor patch validation to versioned operation parser
- move canonical ID from doc to method metadata
Closes #277

chore: update sidetree-core - move canonical ID to method metadata

---

go.mod
go.sum
pkg/httpserver/server_test.go
pkg/mocks/protocol.go
pkg/observer/observer_test.go
scripts/integration.sh
test/bddtests/did_sidetree_steps.go
test/bddtests/features/did-sidetree.feature
test/bddtests/go.mod
test/bddtests/go.sum

Included:
- update sidetree-core version (SIP-2; models moved to versioned folder)
- enable interop tests
Closes #279

chore: update sidetree-core (SIP-2, models versioned)

---

cmd/sidetree-server/main.go
go.mod
go.sum
test/bddtests/did_sidetree_steps.go
test/bddtests/features/interop.feature
test/bddtests/fixtures/docker-compose.yml
test/bddtests/go.mod
test/bddtests/go.sum

Sidetree-core has been updated to support optional @base property. Now we can have exact match tests against reference application.
Note: two interop tests for exact match are commented out until reference application fixes https://github.com/decentralized-identity/sidetree/issues/905
Closes #287

chore: add interop tests with exact match

---

go.mod
go.sum
test/bddtests/did_sidetree_steps.go
test/bddtests/features/interop.feature
test/bddtests/go.mod
test/bddtests/go.sum

- handle purpose as per latest spec
Enable exact match interop tests since reference app purpose issue has been closed.
Closes #289

chore: enable exact match interop tests

---

go.mod
go.sum
pkg/mocks/protocol.go
pkg/observer/observer_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

- signed data loaded from proof files
- renamed anchor/map file to core/provisional index
- adjusted protocol parameter names accordingly
- kid MAY be present in the protected headers
Closes #295

chore: signed data loaded from proof files

---

go.mod
go.sum
pkg/httpserver/server_test.go
pkg/mocks/protocol.go
pkg/observer/observer_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Included:
- SIP-1
- Checks for commitment re-use within an operation (client, server side)
- Align interfaces/code with anticipated pruning/checkpoint requirements
- Remove "kid must be present in protected header" rule in the client
- Max operation size parameter similar to protocol (1 vs 2 kilobytes - it fails)
Closes #301

chore: update sidetree-core (SIP-1)

---

go.mod
go.sum
pkg/mocks/protocol.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

Included:
- new protocol parameters: max delta, max proof, max hash plus related REST validation and batch validation
- validation of max operation size moved to operation parser (before un-marshalling)
- move canonicalId to did document metadata
- validate CAS file URIs (new protocol parameter max CAS URI length)
- add-services will now fail if there are duplicate services
- advance update commitment if possible
Closes #305

chore: update sidetree-core (max delta, proof, hash, cas uri)

---

go.mod
go.sum
pkg/httpserver/server_test.go
pkg/mocks/protocol.go
pkg/observer/observer_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/features/did-sidetree.feature
test/bddtests/go.mod
test/bddtests/go.sum

Complete SIP-1:
- add reveal value in update, reveal, deactivate operations
- support multiple multi-hashing algorithms in protocol
- remove max proof size protocol parameter
Also, added REST API check to fail create if applying patches results in an empty document (due to an error or invalid usage)
Closes #311

chore: update sidetree-core (reveal value added to requests)

---

go.mod
go.sum
pkg/mocks/protocol.go
test/bddtests/did_sidetree_steps.go
test/bddtests/features/did-sidetree.feature
test/bddtests/go.mod
test/bddtests/go.sum

Update sidetree-core and add integration tests for re-using keys for did operations.
Closes #324

chore: Add BDD test for reusing keys for did operation

---

cmd/sidetree-server/main.go
go.mod
go.sum
pkg/httpserver/server_test.go
pkg/mocks/protocol.go
pkg/observer/observer_test.go
test/bddtests/did_sidetree_steps.go
test/bddtests/go.mod
test/bddtests/go.sum

- new decompression factor protocol paramters
- handler endpoints should be passed in to core operation and resolution handlers
- renamed versions folder from 0_1 to 1_0
Closes #326

chore: update sidetree-core (decompression factor, handler endpoints)

---

scripts/integration.sh
test/bddtests/did_sidetree_steps.go
test/bddtests/features/interop.feature
test/bddtests/jsondiff/jsondiff.go

There are differences between reference app results and sidetree core results due to core having two additional fields (created, equivalent ID). Also, reference app has additional context.
Created expected mismatch results for create, update, recover, deactivate and long form requests that reflect the above mentioned differences and enabled interop tests.
Closes  #338

chore: Fix and enable interop tests
